[project]
name = "async-python-talk"
version = "0.1.0"
description = "Async Python talk"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.14.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
